### ISSUE TITLE
[technical] Migrate Flutter Dribble Nike to Flutter 2.0

### ISSUE THREAD

**Issue by joshuadeguzman** [joshuadeguzman/flutter-examples#12]
## Resources
- https://dart.dev/null-safety/migration-guide

**Comment by M-A-D-A-R-A** [comment]
hey I would like to work on this issue .

**Comment by joshuadeguzman** [comment]
> hey I would like to work on this issue .

Awesome! Thank you @M-A-D-A-R-A, let me know if you need anything.
