### ISSUE TITLE
[technical] Migrate Flutter Moviehub to Flutter 2.0

### ISSUE THREAD

**Issue by joshuadeguzman** [joshuadeguzman/flutter-examples#14]
## Resources
- https://dart.dev/null-safety/migration-guide

**Comment by danger-ahead** [comment]
Hi! I can help with this. Please consider assigning me!

**Comment by joshuadeguzman** [comment]
> Hi! I can help with this. Please consider assigning me!

Awesome! Goodluck @danger-ahead. Let me know if you need anything.

**Comment by danger-ahead** [comment]
> > Hi! I can help with this. Please consider assigning me!
> 
> Awesome! Goodluck @danger-ahead. Let me know if you need anything.

Kindly have a look!
On a different note, I've just started learning flutter. This is an amazing repo.
