### ISSUE TITLE
[technical] Migrate Flutter Firestore CRUD to Flutter 2.0

### ISSUE THREAD

**Issue by joshuadeguzman** [joshuadeguzman/flutter-examples#16]
## Resources
- https://dart.dev/null-safety/migration-guide
- https://codewithandrea.com/articles/migrating-flutter-firebase-app-null-safety/

**Comment by abdlrhmanshehatamoussa** [comment]
Hi there,
I can work on this if there is no body working...

**Comment by joshuadeguzman** [comment]
Feel free @abdlrhmanshehatamoussa! Thank you and goodluck, let me know if you need anything!
