### ISSUE TITLE
UnDraw Depende

### ISSUE THREAD

**Issue by jeandersoncruz** [joshuadeguzman/flutter-examples#4]
After setup the project I'm having the following issue:

Launching lib/main.dart on Mate 20 Pro in debug mode...

Compiler message:
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.13.1/lib/src/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  PictureStream();
  ^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.13.1/lib/src/picture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
abstract class PictureStreamCompleter extends Diagnosticable {
               ^

Compiler message:
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.13.1/lib/src/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  PictureStream();
  ^^^^^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.13.1/lib/src/picture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
abstract class PictureStreamCompleter extends Diagnosticable {
                         ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/jcn/flutter-apps/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 883

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/jcn/flutter-apps/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

After debugging some part of the code I found out that is related to the UnDraw Plugin.

**Comment by joshuadeguzman** [comment]
Hey @jeandersoncruz, can you share your `flutter doctor -v` logs? Thank you.

**Comment by miladz9889** [comment]
@joshuadeguzman - I'm running into the same issue after using the undraw package. See below terminal output and also attached flutter doctor -v logs:

Compiler message:
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.13.1/lib/src/pi
cture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed
constructor that takes no arguments.
  PictureStream();                                                      
  ^^^^^^^^^^^^^                                                         
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.13.1/lib/src/pi
cture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed
constructor that takes no arguments.
abstract class PictureStreamCompleter extends Diagnosticable {          
               ^                                                        
Running Xcode build...                                                  
                                                   
Xcode build done.                                           17.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳

    Compiler message:
    ../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.13.1/lib/sr
    c/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no
    unnamed constructor that takes no arguments.
      PictureStream();
      ^^^^^^^^^^^^^
    ../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.13.1/lib/sr
    c/picture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no
    unnamed constructor that takes no arguments.
    abstract class PictureStreamCompleter extends Diagnosticable {
                   ^
    Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
    build failed.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: Capabilities for Signing & Capabilities may not function correctly
    because its entitlements use a placeholder team ID. To resolve this, select a
    development team in the Runner editor. (in target 'Runner' from project
    'Runner')
    warning: Skipping duplicate build file in Copy Bundle Resources build phase:
    /Users/miladsmacbook/Development/Projects/DailyChallangeApp/ios/Runner/GoogleSer
    vice-Info.plist (in target 'Runner' from project 'Runner')

octor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.19.0-2.0.pre.145, on Mac OS X 10.15.4 19E287, locale
    en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
miladsmacbook@Milads-MacBook-Pro DailyChallangeApp % flutter doctor -v    
[✓] Flutter (Channel master, 1.19.0-2.0.pre.145, on Mac OS X 10.15.4 19E287, locale
    en-US)
    • Flutter version 1.19.0-2.0.pre.145 at
      /Users/miladsmacbook/Development/Tools/flutter
    • Framework revision af9b6a6efa (5 hours ago), 2020-05-26 09:17:55 -0700
    • Engine revision 9ce1e5c5c7
    • Dart version 2.9.0 (build 2.9.0-10.0.dev 7706afbcf5)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/miladsmacbook/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • AD605FB7-F665-44B7-9BB4-DCC1C92674F3 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

**Comment by joshuadeguzman** [comment]
I think this is indeed related to the UnDraw plugin. It's currently building on stable channel, 1.12.13. I'll have it replaced soon so it won't affect anyone using the latest SDK versions.

For the meantime, @jeandersoncruz  and @miladz9889, could you please try removing the UnDraw dependency from the project and try to create build?

Thank you!

**Comment by miladz9889** [comment]
@joshuadeguzman I found the following [link](https://github.com/westdabestdb/undraw/issues/11#issuecomment-626304069) that fixed it for me. 

Thanks!
